### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by AidenWedema** [Tee1er/boing#10]
i followed all steps and everything went well, but when i try to run the run.bat file nothing hapens...

i have JRE 8 and just downloaded node 16.6.1 here: https://nodejs.org/download/release/v16.6.1/

**Comment by Tee1er** [comment]
Might need a bit more information to help you; Could you maybe send like a
screenshot of your console prior when running the program? Also, I'm
assuming you're on Windows, but if you are on Linux make sure to run the
equivalent run.sh file.

**Comment by Tee1er** [comment]
(*sorry, prior shouldn't have been there) Just a screenshot of the console
when you start Boing would be great.

Usually you should get something like this
![image](https://user-images.githubusercontent.com/67598882/155415029-1c0f7bfe-bcb9-4229-a62c-ec1b153e2193.png)

**Comment by AidenWedema** [comment]
I am on windows.
I didn't use the console... i just double clicked on the run.bat file. this opens a console, but then it immediately closes
When trying to load the file via console both the windows console and node throw an error...
![image](https://user-images.githubusercontent.com/100278160/155561661-093bb108-bb4e-4de2-80e5-ea9874ae141f.png)
![image](https://user-images.githubusercontent.com/100278160/155561848-39a5ff7e-86af-40dd-a67c-e965a0e4f941.png)

**Comment by Tee1er** [comment]
Oh, I think I might know what the issue is here.
When you installed Node.js, did you make sure to check the Install to PATH box? Otherwise, Boing probably won't work. 
You can check whether or not you did that by just opening up a terminal, and typing in `node --version`
If it returns an error, the easiest way to fix it probably just to uninstall Node and reinstall it, making sure to check that box. Sorry, I should've made that more clear in the README.

**Comment by AidenWedema** [comment]
reinstalling node worked, thanks

**Comment by Tee1er** [comment]
No problem!
